appName: "onix-local"
log:
  level: debug
  destinations:
    - type: stdout
  contextKeys:
    - transaction_id
    - message_id
    - subscriber_id
    - module_id
http:
  port: 8082
  timeout:
    read: 30
    write: 30
    idle: 30
pluginManager:
  root: ./plugins
modules:
  - name: bppTxnReceiver
    path: /bpp/receiver/
    handler:
      type: std
      role: bpp
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: https://fabric.nfh.global/registry/dedi
            registryName: subscribers.beckn.one
            timeout: 10
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: sandbox.open-kitchen.com
            keyId: 76EU8h2x8sGsY9c659SFNT7pJEJntehLHfr3p4oXVy3mCDMn5GFiMg
            signingPrivateKey: 4YRjrBFInRb8OLN1PiwUM9qutrJy2bvzcWPNy47VAD4=
            signingPublicKey: AAUhITzcjMbmPikr/UV5T8/Zp8+NWZ/NrVVateA5eiQ=
            encrPrivateKey: 4YRjrBFInRb8OLN1PiwUM9qutrJy2bvzcWPNy47VAD4=
            encrPublicKey: AAUhITzcjMbmPikr/UV5T8/Zp8+NWZ/NrVVateA5eiQ=
        schemaValidator:
          id: schemav2validator
          config:
            type: url
            location: https://raw.githubusercontent.com/beckn/protocol-specifications-v2/refs/tags/core-v2.0.0-lts/api/v2.0.0/beckn.yaml
            cacheTTL: "3600"
            extendedSchema_enabled: "false"
            extendedSchema_cacheTTL: "86400"
            extendedSchema_maxCacheSize: "100"
            extendedSchema_downloadTimeout: "30"
            extendedSchema_allowedDomains: "raw.githubusercontent.com,schema.beckn.io"
        cache:
          id: cache
          config:
            addr: redis:6379
        signValidator:
          id: signvalidator
        router:
          id: router
          config:
            routingConfig: ./config/local-simple-routing-BPPReceiver.yaml
      steps:
        - validateSign
        - addRoute
        - validateSchema
  
  - name: bppTxnCaller
    path: /bpp/caller/
    handler:
      type: std
      role: bpp
      httpClientConfig:
        maxIdleConns: 1000
        maxIdleConnsPerHost: 200
        idleConnTimeout: 300s
        responseHeaderTimeout: 5s
      plugins:
        registry:
          id: dediregistry
          config:
            url: https://fabric.nfh.global/registry/dedi
            registryName: subscribers.beckn.one
            timeout: 10
            retry_max: 3
            retry_wait_min: 100ms
            retry_wait_max: 500ms
        keyManager:
          id: simplekeymanager
          config:
            networkParticipant: sandbox.open-kitchen.com
            keyId: 76EU8h2x8sGsY9c659SFNT7pJEJntehLHfr3p4oXVy3mCDMn5GFiMg
            signingPrivateKey: 4YRjrBFInRb8OLN1PiwUM9qutrJy2bvzcWPNy47VAD4=
            signingPublicKey: AAUhITzcjMbmPikr/UV5T8/Zp8+NWZ/NrVVateA5eiQ=
            encrPrivateKey: 4YRjrBFInRb8OLN1PiwUM9qutrJy2bvzcWPNy47VAD4=
            encrPublicKey: AAUhITzcjMbmPikr/UV5T8/Zp8+NWZ/NrVVateA5eiQ=
        schemaValidator:
          id: schemav2validator
          config:
            type: url
            location: https://raw.githubusercontent.com/beckn/protocol-specifications-v2/refs/tags/core-v2.0.0-lts/api/v2.0.0/beckn.yaml
            cacheTTL: "3600"
            extendedSchema_enabled: "true"
            extendedSchema_cacheTTL: "86400"
            extendedSchema_maxCacheSize: "100"
            extendedSchema_downloadTimeout: "30"
            extendedSchema_allowedDomains: "raw.githubusercontent.com,schema.beckn.io"
        cache:
          id: cache
          config:
            addr: redis:6379
        router:
          id: router
          config:
            routingConfig: ./config/local-simple-routing-BPPCaller.yaml
        signer:
          id: signer
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bpp          
      steps:
        - addRoute
        - sign
        - validateSchema