routingRules:
  - version: "2.0.0"
    targetType: "bap"
    endpoints:
      - on_select
      - on_init
      - on_confirm
      - on_status
      - on_cancel
      - on_support
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://fabric.nfh.global/beckn/catalog"
    endpoints:
      - publish
