routingRules:
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "http://sandbox-bpp:3002/api/webhook"
    endpoints:
      - select
      - init
      - confirm
      - status
      - cancel
      - support
