routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - cancel
      - support
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://34.14.221.66.sslip.io/beckn"
    endpoints:
      - discover
